Изменил SQL запросы, исправил ошибку в подключении к БД, создал сущно…
Valfurion/VehicleShop pull request #3
Opened 2020-01-07 19:57 UTC by Valfurion

…сти с контроллерами и репозиториями.

Сделал возможность отображния всех двигателей и типов двигателей по их id

2020-01-07 20:01 UTC, AlexanderMv88 commented on src/main/java/org/VehicleShop/entity/Engine.java
> +private  Long engineId;
Не забывай использовать ctrl+alt+l

2020-01-07 20:03 UTC, AlexanderMv88 commented on src/main/java/org/VehicleShop/repository/EngineRepository.java
> +            engine.setEngineId(resultSet.getLong("Engine_id"));
Engine_id с маленькой буквы

2020-01-07 20:04 UTC, AlexanderMv88 commented on src/main/java/org/VehicleShop/repository/EngineRepository.java
> +            engine.setEngineTypeId(resultSet.getLong("Engine_Type_Id"));
Engine_Type_Id с маленькой буквы

2020-01-07 20:04 UTC, AlexanderMv88 commented on src/main/java/org/VehicleShop/repository/EngineTypeRepository.java
> +            engineType.setEngineTypeId(resultSet.getLong("Engine_type_id"));
Engine_Type_Id с маленькой буквы

2020-01-07 20:06 UTC, AlexanderMv88 commented on SQL
> +
А где выборка всех vehicle с engine_type_title?
А где выборка vehicle с engine_type_title по vehicle_id?

2020-01-07 20:07 UTC, AlexanderMv88 commented on SQL
> +
А где выборка engine по id?

2020-01-07 20:07 UTC, AlexanderMv88 requested changes
Есть замечания

2020-01-08 18:05 UTC, AlexanderMv88 commented on SQL
> +--left join vehicle.engine e on v.engine_id=e.engine_id
Добавь связь vehicle_type и выведи данные о типе vehicle

2020-01-08 18:12 UTC, AlexanderMv88 commented on src/main/java/org/VehicleShop/entity/Engine.java
> +    private Long engineTypeId;
В сущности Engine должны содержаться сущность EngineType, а у тебя Long engineTypeId

2020-01-08 18:14 UTC, AlexanderMv88 requested changes
Нужны доработки

2020-01-09 15:13 UTC, AlexanderMv88 commented on SQL
> +--create table vehicle.engine (engine_id bigserial primary key, title varchar (255) NOT NULL, volume varchar (20) NOT NULL, engine_type_id bigserial, engine_type_title varchar (255));
Vehicle.engine не должна содержать поле engine_type_title

2020-01-09 15:16 UTC, AlexanderMv88 commented on SQL
> +--***выборка vehicle с vehicle_type_title,engine_type_title, engine_title, volume, по vehicle_id***--
Не верный коммент. Тут выборка производится не по vehicle_id

2020-01-09 15:18 UTC, AlexanderMv88 commented on SQL
> +--***выборка всех vehicle с engine_type_title***--
Этот sql не нужен. Он неполный да и вобще лишний

2020-01-09 15:19 UTC, AlexanderMv88 requested changes
Есть замечания

2020-01-09 15:41 UTC, Valfurion commented on SQL
> +--create table vehicle.engine (engine_id bigserial primary key, title varchar (255) NOT NULL, volume varchar (20) NOT NULL, engine_type_id bigserial, engine_type_title varchar (255));
исправил:
1) Убрал поле engine_type_title
2) Переименовал поле title на engine_type_title в таблице vehicle.engine_type
3)Переименовал поле title на vehicle_type_title в таблице vehicle.vehicle_type
т.к. в дальнейшем все написано под такие названия, что упрощает код.
![Скриншот 09-01-2020 184203](https://user-images.githubusercontent.com/59439224/72081524-b278ab00-330f-11ea-8ad8-626cbf0f6031.png)

2020-01-09 15:43 UTC, Valfurion commented on SQL
> +--***выборка vehicle с vehicle_type_title,engine_type_title, engine_title, volume, по vehicle_id***--
Исправил
![Скриншот 09-01-2020 184332](https://user-images.githubusercontent.com/59439224/72081687-f966a080-330f-11ea-9f7e-6140323369b0.png)

2020-01-09 18:04 UTC, AlexanderMv88 commented on src/main/java/org/VehicleShop/controller/EngineTypeController.java
> +    public EngineType engineTypes(@PathVariable Long id) {
Ты получаешь engineType по id, а не engineTypes. Нужно переименовать метод.

2020-01-09 18:05 UTC, AlexanderMv88 commented on src/main/java/org/VehicleShop/entity/Engine.java
> +    private EngineType engineType;
Поле engineType надо поднять на строку 7

2020-01-09 18:07 UTC, AlexanderMv88 requested changes
Есть замечания в java коде

2020-01-09 20:03 UTC, AlexanderMv88 approved these changes
ЗБС

2020-01-09 20:05 UTC, merged